[package]
name = "rld-fast-payments"
version = "0.1.0"
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
rld-core = { path = "../rld-core" }
rld-pow = { path = "../rld-pow" }
hex.workspace = true
serde.workspace = true
serde_json.workspace = true
sha2.workspace = true
